<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'ENV_CONFIG' => '.dev',
  'ESTRUCTURA_1' => '1',
  'accion_registrar' => '1',
  'accion_modificar' => '2',
  'accion_eliminar' => '3',
  'accion_inicio_sesion' => '4',
  'accion_cierre_sesion' => '5',
  'tipo_traza_sesion' => '1',
  'tipo_traza_negocio' => '2',
  'objeto_autenticacion' => '1',
  'objeto_institucion' => '2',
  'objeto_solicitud_programa' => '3',
  'id_categoria_estructura_ies' => '17',
  'id_categoria_estructura_facultad' => '2',
  'APP_SECRET' => '1',
  'DATABASE_URL' => 'postgresql://postgres:postgres@127.0.0.1:5432/bd_akademos_mes',
  'JWT_SECRET_KEY' => '%kernel.project_dir%/config/jwt/private.pem',
  'JWT_PUBLIC_KEY' => '%kernel.project_dir%/config/jwt/public.pem',
  'JWT_PASSPHRASE' => '2ada32e38578467b3916d53ea6f413e5',
  'BASE_URL' => '',
  'IB_API_RI_URL' => 'http://relaciones_internacionales.local',
  'DB_HOST' => 'localhost',
  'DB_USER' => 'postgres',
  'DB_PASS' => 'postgres',
  'DB_PORT' => '5432',
  'DB_NAME' => 'BD_sgu_nucleo',
);
